#!/bin/sh
start(){
	cd /data/data/cserv/pythonCode/serviringest/sh/operational
	./runWorkers.sh start
}
stop() {
	cd /data/data/cserv/pythonCode/serviringest/sh/operational
        ./runWorkers.sh stop
}




case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
