#!/bin/sh
start(){
        sudo /etc/rc.d/init.d/httpd start
}
stop() {
        sudo /etc/rc.d/init.d/httpd stop
}




case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

